name: Build ImmortalWrt for MT798x

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      device:
        description: 'Target device (e.g., mt7981-ax3000, mt7986-ax6000, mt7986-ax6000-256m)'
        required: true
        default: 'mt7981-ax3000'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget qemu-utils ccache device-tree-compiler \
            xsltproc python3-dev python3-pip subversion swig curl time

      - name: Clone ImmortalWrt source
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
          cd immortalwrt-mt798x
          git checkout openwrt-21.02

      - name: Update and install feeds
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy configuration
        run: |
          cd immortalwrt-mt798x
          cp -f defconfig/${{ github.event.inputs.device || 'mt7981-ax3000' }}.config .config

      - name: Configure build
        run: |
          cd immortalwrt-mt798x
          make defconfig
          make menuconfig -j1 V=s

      - name: Build firmware
        run: |
          cd immortalwrt-mt798x
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt-mt798x/bin/targets/mediatek/mt7981/
          retention-days: 5
